/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package edu.ijse.layered.view;

import edu.ijse.layered.controller.CustomerController;
import edu.ijse.layered.controller.ItemController;
import edu.ijse.layered.controller.OrderController;
import edu.ijse.layered.dto.CustomerDto;
import edu.ijse.layered.dto.ItemDto;
import edu.ijse.layered.dto.OrderDetailDto;
import edu.ijse.layered.dto.OrderDto;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author osandaindunika
 */
public class OrderView extends javax.swing.JFrame {
    
    private CustomerController customerController;
    private ItemController itemController;
    private OrderController orderController;
    private ArrayList<OrderDetailDto> orderDetailDtos = new ArrayList<>();

    /**
     * Creates new form OrderView
     */
    public OrderView() throws Exception {
        this.customerController = new CustomerController();
        this.itemController = new ItemController();
        this.orderController = new OrderController();
        initComponents();
        loadTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblOrderId = new javax.swing.JLabel();
        txtOrderId = new javax.swing.JTextField();
        lblCustomerId = new javax.swing.JLabel();
        txtCustomerId = new javax.swing.JTextField();
        lblCustDetail = new javax.swing.JButton();
        lblItemCode = new javax.swing.JLabel();
        txtItemCode = new javax.swing.JTextField();
        lblItemDetail = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        lblDiscount = new javax.swing.JLabel();
        txtDiscount = new javax.swing.JTextField();
        btnAddToTable = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblOrderDetail = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        lblItemData = new javax.swing.JLabel();
        lblCustData = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        txtCustId = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Order View");

        lblOrderId.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblOrderId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblOrderId.setText("Order Id");

        txtOrderId.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtOrderId.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblCustomerId.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblCustomerId.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomerId.setText("Customer Id");

        txtCustomerId.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtCustomerId.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblCustDetail.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblCustDetail.setText("Search");
        lblCustDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCustDetailActionPerformed(evt);
            }
        });

        lblItemCode.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblItemCode.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblItemCode.setText("Item Code");

        txtItemCode.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtItemCode.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblItemDetail.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        lblItemDetail.setText("Search");
        lblItemDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblItemDetailActionPerformed(evt);
            }
        });

        lblQty.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("Qty");

        txtQty.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtQty.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        lblDiscount.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblDiscount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDiscount.setText("Discount");

        txtDiscount.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtDiscount.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        btnAddToTable.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnAddToTable.setText("Add");
        btnAddToTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToTableActionPerformed(evt);
            }
        });

        tblOrderDetail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblOrderDetail);

        lblItemData.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        lblItemData.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblCustData.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N

        btnPlaceOrder.setFont(new java.awt.Font("Helvetica Neue", 1, 20)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        txtCustId.setFont(new java.awt.Font("Heiti TC", 0, 20)); // NOI18N
        txtCustId.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnPlaceOrder))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblQty)
                                .addGap(398, 398, 398)
                                .addComponent(lblDiscount)
                                .addGap(38, 38, 38)
                                .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(66, 66, 66)
                                .addComponent(btnAddToTable))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblItemCode)
                                        .addGap(45, 45, 45)
                                        .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(139, 139, 139)
                                .addComponent(lblItemDetail)
                                .addGap(27, 27, 27)
                                .addComponent(lblItemData, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblCustomerId)
                                        .addGap(30, 30, 30))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblOrderId)
                                        .addGap(68, 68, 68)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtOrderId, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(txtCustId))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCustDetail)
                                .addGap(28, 28, 28)
                                .addComponent(lblCustData, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 27, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOrderId)
                    .addComponent(txtOrderId, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblCustomerId)
                                    .addComponent(txtCustId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCustDetail))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(5, 5, 5)
                                    .addComponent(txtCustomerId, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblCustData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblItemCode)
                            .addComponent(txtItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblItemDetail)))
                    .addComponent(lblItemData, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQty)
                    .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblDiscount)
                        .addComponent(txtDiscount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnAddToTable)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPlaceOrder)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddToTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToTableActionPerformed
        addToTable();
    }//GEN-LAST:event_btnAddToTableActionPerformed

    private void lblCustDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCustDetailActionPerformed
        searchCustomer();      
    }//GEN-LAST:event_lblCustDetailActionPerformed

    private void lblItemDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblItemDetailActionPerformed
       searchItem(); 
    }//GEN-LAST:event_lblItemDetailActionPerformed

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
       placeOrder();
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(OrderView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//             public void run() {
//                new OrderView().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddToTable;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCustData;
    private javax.swing.JButton lblCustDetail;
    private javax.swing.JLabel lblCustomerId;
    private javax.swing.JLabel lblDiscount;
    private javax.swing.JLabel lblItemCode;
    private javax.swing.JLabel lblItemData;
    private javax.swing.JButton lblItemDetail;
    private javax.swing.JLabel lblOrderId;
    private javax.swing.JLabel lblQty;
    private javax.swing.JTable tblOrderDetail;
    private javax.swing.JTextField txtCustId;
    private javax.swing.JTextField txtCustomerId;
    private javax.swing.JTextField txtDiscount;
    private javax.swing.JTextField txtItemCode;
    private javax.swing.JTextField txtOrderId;
    private javax.swing.JTextField txtQty;
    // End of variables declaration//GEN-END:variables

    private void searchCustomer(){
        try {
            String custId = txtCustId.getText();
             CustomerDto customerDto = customerController.searchCustomer(custId);
            if(customerDto != null){
                lblCustData.setText(customerDto.getTitle() + " " + customerDto.getName() + " | " + customerDto.getAddress());
            } else {
                lblCustData.setText("Customer Not Found.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void searchItem() {
         try {
            String itemId = txtItemCode.getText();
            ItemDto itemDto = itemController.get(itemId);
            if(itemDto != null){
                lblItemData.setText(itemDto.getDescription() + " | " + itemDto.getPack() + " | " + itemDto.getQoh() +"pck" + " | " + "Rs." + itemDto.getUnitPrice());
            } else {
                lblItemData.setText("Item Not Found.");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }
    
      private void addToTable(){
        OrderDetailDto orderDetailDto = new OrderDetailDto();
        orderDetailDto.setDiscount(Integer.parseInt(txtDiscount.getText()));
        orderDetailDto.setItemCode(txtItemCode.getText());
        orderDetailDto.setQty(Integer.parseInt(txtQty.getText()));
        
        orderDetailDtos.add(orderDetailDto);
        
        Object[] rowData = {orderDetailDto.getItemCode(), orderDetailDto.getQty(), orderDetailDto.getDiscount()};
        DefaultTableModel dtm = (DefaultTableModel) tblOrderDetail.getModel();
        dtm.addRow(rowData);
        
        clearItem();
    }
    
    private void clearItem(){
        txtItemCode.setText("");
        txtQty.setText("");
        txtDiscount.setText("");
        lblItemData.setText("");
    }

    private void loadTable() {
        String columns[] = {"Item Code", "Qty", "Discount"};
        DefaultTableModel dtm = new DefaultTableModel(columns, 0){
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        tblOrderDetail.setModel(dtm);
    }
    
     private void placeOrder() {
        try {
            OrderDto orderDto = new OrderDto();
            orderDto.setCustId(txtCustId.getText());
            orderDto.setOrderId(txtOrderId.getText());

             //2008-02-05 -> 
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            String date = sdf.format(new Date());
            orderDto.setDate(date);
            
            orderDto.setOrderDetailDtos(orderDetailDtos);
            
            String resp = orderController.placeOrder(orderDto);
            JOptionPane.showMessageDialog(this, resp);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }

    }
    
}
